name: flutter_scan_bluetooth
description: Flutter plugin to scan Bluetooth devices.
version: 1.2.2
homepage: https://github.com/kiwi-bop/flutter_scan_bluetooth

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kiwi.flutterscanbluetooth
        pluginClass: FlutterScanBluetoothPlugin
      ios:
        pluginClass: FlutterScanBluetoothPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.20.0"
